### PR TITLE
common html tags + common files ext

### LINKED ISSUE #2: [bug] KeyError: 'href' error
If html output contains namespace e.g. `<a xlink:href="./foo/bar/">` then `file['href']` from loop: https://github.com/JonasDoesThings/mkdocs-exclude-unused-files/blob/aceb9e261c4bb425bbb425cbce446563ecde4831/mkdocs_exclude_unused_files/plugin.py#L61

throw

```
ERROR    -  Error building page 'README.md': 'href'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 234, in _build_page
    output = config.plugins.run_event('post_page', output, page=page, config=config)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/mkdocs_exclude_unused_files/plugin.py", line 62, in on_post_page
    self.asset_files.discard(str(Path(path.join(path.dirname(page.file.abs_dest_path), unquote(file['href']))).resolve()))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/bs4/element.py", line 1529, in __getitem__
    return self.attrs[key]
KeyError: 'href'
```

proposed solution:

```python
for file in soup.find_all("a", {'href': True}):
```

it will scraping only valid links.

fix with abstraction proposed in: https://github.com/JonasDoesThings/mkdocs-exclude-unused-files/pull/1

### PR DESCRIPTION
**Pull request by DariuszPorowski**
- Added missing html tags that contains link to something.
- Added common extensions used as attached files to *.md documentation (like audio, video, office files, office files templates, archives, ...)
- #2 fix proposal + abstraction (close #2)

### CODE REVIEW

**Comment by DariuszPorowski** [comment]
ps
@JonasDoesThings good work on this plugin, you solve my problem and do not have to write my own plugin that I had on my todo list.

**Comment by JonasDoesThings** [comment]
Hey, thanks for your contribution :) 

Looks good to me at first glance, I will test it out after work and release a new version with the changes if everything works! 👍

**Comment by DariuszPorowski** [comment]
oh, one more thing. Have you considered lxml instead of BeautifulSoup? I think performance may improve.

**Comment by JonasDoesThings** [comment]
> oh, one more thing. Have you considered lxml instead of BeautifulSoup? I think performance may improve.

There's a ToDo comment in https://github.com/JonasDoesThings/mkdocs-exclude-unused-files/blob/main/mkdocs_exclude_unused_files/plugin.py#L58 regarding the ability to configure custom parsers.

BeautifulSoup allows using lxml as a parser, but since it's an external dependency, I've gone with the built-in one by default. I could probably just add a configuration value allowing to configure other supported parsers, and let the user handle installing / providing them.

**Comment by DariuszPorowski** [comment]
actually, my point is to use lxml natively not via BeautifulSoup

**Comment by JonasDoesThings** [comment]
Looks good to me in gernal, the only thing I don't quite understand is the usage of `defaultdict` - that said, I'm not a Python pro - so could you tell me, what advantages the usage of `defaultdict` has here? 

I looked up the docs, but cannot identify why it's neccessary in this part of code, since caling .items() even on a normal dict should never produce a KeyError, since we are not accessing the dict directly. Is the performance of defaultdict better, or is it just precaution?

Regarding the usage of lxml natively, does this really provide an advantage (performance-wise?) compared to allowing the user to configure the parser they want to use with BeautifulSoup themselves? 

Cheers from Austria and thanks for your contribution!

**Comment by DariuszPorowski** [comment]
Hey @JonasDoesThings 
actually, for this case defaultdict is useless - just my habit from different projects where sometimes you can map lambda function, etc... did commit with the update.

items() return is good in general, but as I mentioned #2, when you are referring after file['href'] and item does not contain href tag itself (in my case it was xlink:href) you will get KeyError. Adding {'href ': True} enforce list to return only items with the strict tag/attrib mapping. In my case xlink:href was part of embedded svg image into html.

As I observed so far lxml is the lightest and fasted xml/html parser. If someone has very large codebase it may generates impact.

Greetings from USA :)

**Review by JonasDoesThings — APPROVED** [review]
LGTM

**Comment by JonasDoesThings** [comment]
The new release containing this code is also live now:
https://pypi.org/project/mkdocs-exclude-unused-files/1.1.0/

Regarding lxml; I've looked more into it, looks cool, also it can even use [BeautifulSoup's parser as a fallback](https://lxml.de/elementsoup.html#using-soupparser-as-a-fallback) in some edge-cases. If you want to go further with that, feel free to open an additional Issue or PR! Cheers

**Pull request merged**
